#
# Test building the Debian package and run tests in a virtual environment
#

when:
  event: [push, tag, pull_request, manual]

steps:
  
  deb:
    image: debian:sid
    commands:
      - export CI=true
      - export DEBIAN_FRONTEND=noninteractive
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - apt update
      - apt install -y --no-install-recommends build-essential python3 python3-venv flit dh-python pybuild-plugin-pyproject debhelper
      - make deb

  pytest:
    image: debian:sid
    commands:
      - export CI=true
      - export DEBIAN_FRONTEND=noninteractive
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - apt update
      - apt install -y --no-install-recommends build-essential python3 python3-venv
      - python3 -m venv venv && . ./venv/bin/activate && pip install pytest && pip install -e .
      - . ./venv/bin/activate && pytest -vvv
