[project]
name = "reunion"
description = "reunion is for rendezvous"
version = "1.0.0"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[testenv]
commands = ["pytest"]
[tool.setuptools]
packages = ["reunion"]
