[project]
name = "reunion"
version = "1.0"
description = "reunion description"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
packages = ["reunion"]
